server:
  port: 80
#spring:
#  datasource:
#    name: test  #数据库名
#    url: jdbc:mysql://localhost:3306/test #url
#    username: root  #用户名
#    password: root #密码
#    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件

